### ISSUE TITLE
When I sign up for a task, I don't receive a notification

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas-open-opportunities#69]
```
/var/www/midas/node_modules/underscore/underscore.js:1304
    text.replace(matcher, function(match, escape, interpolate, evaluate, offse
         ^
TypeError: Cannot call method 'replace' of undefined
    at Function._.template (/var/www/midas/node_modules/underscore/underscore.js:1304:10)
    at /var/www/midas/api/services/preflight/prepareTaskVolunteer.js:58:42
    at /var/www/midas/api/services/utils/user.js:807:24
    at returnResults (/var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:356:9)
    at /var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:251:16
    at /var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
    at Object.async.each (/var/www/midas/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
    at /var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:425:11
    at /var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:564:5
    at Object.async.each (/var/www/midas/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
    at _buildChildOpts (/var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:453:9)
    at _execChildOpts (/var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:421:8)
    at /var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:80:10
    at bound (/var/www/midas/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
    at wrappedCallback (/var/www/midas/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
```

**Comment by ultrasaurus** [comment]
I think this happens if someone doesn't have an agency filled in:

In /api/services/preflight/prepareTaskVolunteer.js:
```
          volunteer.location = volunteer.location || {};
          volunteer.location.tag = volunteer.location.tag || {};
          volunteer.location.tag.name = volunteer.location.tag.name || '';
          volunteer.agency = volunteer.agency || {};
          volunteer.agency.tag = volunteer.agency.tag || {};
          volunteer.agency.tag.name = volunteer.agency.tag.name || '';
```

**Comment by ultrasaurus** [comment]
ok, never mind my comment on further look should be able to reference undefined property of empty object ```{}``` in JavaScript :)

PR looks good!
